service: serverless-express-boilerplate

provider:
  name: aws
  runtime: nodejs10.x
  region: ${opt:region, "eu-north-1"}
  profile: ${opt:profile}
  stage: ${opt:stage, "dev"}
  tracing: true # enable tracing
  environment:
    ACCOUNTS_TO_BE_CHECKED: ${env:ACCOUNTS_TO_BE_CHECKED}
    SES_EMAIL_SENDER: ${env:SES_EMAIL_SENDER}
  iamRoleStatements:
    - Effect: "Allow" # xray permissions (required)
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-plugin-tracing
  - serverless-dotenv-plugin
  - serverless-offline

functions:
  api:
    handler: index.handler
    timeout: 10
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'