service: serverless-express-boilerplate

provider:
  name: aws
  runtime: nodejs10.x
  region: ${opt:region, "eu-north-1"}
  profile: ${opt:profile}
  stage: ${opt:stage, "dev"}

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-offline

functions:
  api:
    handler: index.handler
    timeout: 10
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'